---
mysql_database: wdream
mysql_user: dream
mysql_pass: dreamuser123

setup_user: dream

search_project_path: "/opt/apps/wdream"
console_project_path: "/opt/apps/crawlerapi"
collecte_project_path: "/opt/apps/consoleadmin"