---

- name: known_hosts for gitlab and bitbucket
  shell: ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts; ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts

- name: Clone the search app
  git:
    repo: git@gitlab.com:franck.gryson/search-access-console.git
    dest: "{{ search_project_path }}"
    key_file: "~dream/.ssh/id_rsa"
  tags: "git"

- name: Clone the CollecteApi app
  git:
    repo: https://Codecritics@bitbucket.org/Codecritics/crawlerapi.git
    dest: "{{ collecte_project_path }}"
  tags: "git"

- name: Clone the Admin Console app
  git:
    repo: https://bitbucket.org/prachiyadav/consoleadmin/src/master/
    dest: "{{ console_project_path }}"
  tags: "git"