- roles:
    - { role: initial_setup, tags: setup }
    - { role: php, tags: php, user: dream, remote_user: dream }
    - { role: composer, tags: php, user: dream, remote_user: dream }
    - { role: redis, tags: redis, user: dream, remote_user: dream }
    - { role: mysql, tags: database, user: dream, remote_user: dream }
    - { role: solr, tags: solr, user: dream, remote_user: dream }
    - { role: nginx, tags: nginx, user: dream, remote_user: dream }

#    - { role: docker, tags: docker, user: dream, remote_user: dream }

  hosts:
    - new_dev
  user: dream
  vars:
    users_root:
      - marius
      - prachi
      - prachi2
      - prachi3
      - subbhash
  tasks:
    - name: Clone the Apps from git
      include: apps/clone_apps.yaml
      tags: apps

    - name: Clone the Apps from git
      include: apps/configure.yaml
      tags: apps