---
- name: Setup packages and users
  include: setup.yaml

- name: Configure Iptables
  include:
    iptables.yaml

- name: Create Folder for the apps
  file:
    path: /opt/apps
    state: directory